import AuthProvider from "@/app/context/AuthContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ro">
      <body>
        {" "}
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
